# Generated by Django 6.0.7 on 2026-07-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('COURSE', 'Course Enrollment'), ('JOB', 'Job Application'), ('GENERAL', 'General Enquiry')], max_length=10),
        ),
    ]
